# Generated by Django 4.1.3 on 2022-11-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educationapp", "0002_alter_person_edad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="inversion_educacion",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
