# Generated by Django 4.1.3 on 2022-11-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educationapp", "0003_alter_person_inversion_educacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="estudios_hijos",
        ),
        migrations.AlterField(
            model_name="person",
            name="edad",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="person",
            name="inversion_educacion",
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name="person",
            name="salario",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
