# Generated by Django 4.1.3 on 2022-11-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "educationapp",
            "0004_remove_person_estudios_hijos_alter_person_edad_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="person",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
