# Generated by Django 3.2.5 on 2022-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationapp', '0005_alter_person_latitude_alter_person_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='edad',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='inversion_educacion',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='promedio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
